# Generated by Django 4.2.6 on 2023-10-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessapp', '0002_business_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='ratings_count',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
